
GET http://localhost:3000/usuarios

GET http://localhost:3000/usuarios

POST http://localhost:3000/usuarios
Contet-Type: application/json

{
		"name": "João",
		"email": "joao.doe@gmail.com",
		"senha": "@183190381",
        "telefone": "11999999999",
        "endereco": "Guaratiba"

}

PATCH  http://localhost:3000/usuarios

DELETE http://localhost:3000/usuarios