//produtos
GET http://localhost:3000/produtos

###

GET http://localhost:3000/produtos

###

POST http://localhost:3000/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXZfdzJtWnhZdVBaY2xfTnRfRGUwU1Q2Iiwibm9tZVVzdWFyaW8iOiJsdWNhcyIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzQ4Mjk2MjI4LCJleHAiOjE3NDgyOTk4Mjh9.QwkvT2kFzUEyqVGsEJMhR4tG9sFCI7SmCTtRTMhbla8

{
  
  "nome":"balinha", 
  "descricao":"teste1",
  "preco": 1.50, 
  "categoria_id":"3",
  "estoque":20 
}

###

PATCH  http://localhost:3000/produtos/dev_upyFxt-jne7jRUVlPmDyW
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXZfREo4dVFTY09MWDF1cEI0dnR4TXFFIiwibm9tZVVzdWFyaW8iOiJqZWZmZXJzb24iLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc0ODI5NTkyMiwiZXhwIjoxNzQ4Mjk5NTIyfQ.7_dbBoIuu1rAbLAyGjuLlZK8qpaCaZU45ygwgUsCd7g

{
  "nome":"pedra", 
  "descricao":"teste",
  "preco": 7.78, 
  "categoria_id":"1",
  "estoque":20 
}

###

DELETE http://localhost:3000/produtos/dev_8HG2CbeQ47wBdS3MZrATu
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXZfWnNKdWRpMXFpZEF0dFQxXzR3MHduIiwibm9tZVVzdWFyaW8iOiJKZWZmZXJzb24gUm9kcmlndWVzIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NDgzMDQ2NzQsImV4cCI6MTc0ODMwODI3NH0.iaLFYimGmPFtu8A3LqBe_ADMYRracI3JKrJRTtFZYzM


###


//carrinho
GET http://localhost:3000/carrinho

GET http://localhost:3000/carrinho

POST http://localhost:3000/carrinho
Content-Type: application/json

{
  "usuario_id": "hjioh54432",
  "total": 1000 
}

PATCH  http://localhost:3000/carrinho

DELETE http://localhost:3000/carrinho


//item-carrinho
GET http://localhost:3000/item_carrinho

GET http://localhost:3000/item_carrinho

POST http://localhost:3000/item_carrinho

PATCH  http://localhost:3000/item_carrinho

DELETE http://localhost:3000/item_carrinho


//categorias

GET http://localhost:3000/categorias

GET http://localhost:3000/categorias

POST http://localhost:3000/categorias
Content-Type: application/json

{
  "nome": "verdura"
}
PATCH  http://localhost:3000/categorias

DELETE http://localhost:3000/categorias


//pedidos
GET http://localhost:3000/pedidos

GET http://localhost:3000/pedidos

POST http://localhost:3000/pedidos

PATCH  http://localhost:3000/pedidos

DELETE http://localhost:3000/pedidos


###

//usuarios
GET http://localhost:3000/usuarios

###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Pedro",
  "email": "jvlegal@example.com",
  "senha": "112233",
  "telefone": "44444444444",
  "endereco": "bairro massa, 1000"
}

###

PATCH  http://localhost:3000/usuarios/

###

DELETE http://localhost:3000/usuarios


//pagamento
GET http://localhost:3000/pagamento

GET http://localhost:3000/pagamento

POST http://localhost:3000/pagamento

PATCH  http://localhost:3000/pagamento

DELETE http://localhost:3000/pagamento


//entrega
GET http://localhost:3000/entrega

GET http://localhost:3000/entrega

POST http://localhost:3000/entrega

PATCH  http://localhost:3000/entrega

DELETE http://localhost:3000/entrega


//endereco
GET http://localhost:3000/endereco

GET http://localhost:3000/endereco

POST http://localhost:3000/endereco

PATCH  http://localhost:3000/endereco

DELETE http://localhost:3000/endereco


//avaliacao
GET http://localhost:3000/avaliacao

GET http://localhost:3000/avaliacao

POST http://localhost:3000/avaliacao

PATCH  http://localhost:3000/avaliacao

DELETE http://localhost:3000/avaliacao