//produtos
GET http://localhost:3000/produtos

###

GET http://localhost:3000/produtos

###

POST http://localhost:3000/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXZfREo4dVFTY09MWDF1cEI0dnR4TXFFIiwibm9tZVVzdWFyaW8iOiJqZWZmZXJzb24iLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc0ODQzNDk3MywiZXhwIjoxNzQ4NDM4NTczfQ.MzhMob4qe3EpkGL8v-1GgrLTd_wAXHlOgtvI0MTevJs

{
  
  "nome":"linguiça de frango",
  "descricao":"Carne bovina moída, ideal para diversos pratos.", 
  "preco": 4.50, 
  "categoria_id":"dev_7vATMgi6tuiNN8adQOnVU",
  "estoque": 50 
}

###

PATCH  http://localhost:3000/produtos/dev__crtGvr2kgoP4sw3Ng1ZO
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXZfWnNKdWRpMXFpZEF0dFQxXzR3MHduIiwibm9tZVVzdWFyaW8iOiJKZWZmZXJzb24gUm9kcmlndWVzIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NDgzOTMyOTAsImV4cCI6MTc0ODM5Njg5MH0.58KsjTWN3JkNFC1uxqFrQFDzfc-ggEsuvevnM_6Ffhg

{
  "nome":"feijao branco"
}

###

DELETE http://localhost:3000/produtos/dev__crtGvr2kgoP4sw3Ng1ZO
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXZfWnNKdWRpMXFpZEF0dFQxXzR3MHduIiwibm9tZVVzdWFyaW8iOiJKZWZmZXJzb24gUm9kcmlndWVzIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NDgzOTMyOTAsImV4cCI6MTc0ODM5Njg5MH0.58KsjTWN3JkNFC1uxqFrQFDzfc-ggEsuvevnM_6Ffhg


###


//carrinho
GET http://localhost:3000/carrinho

GET http://localhost:3000/carrinho

POST http://localhost:3000/carrinho
Content-Type: application/json

{
  "usuario_id": "hjioh54432",
  "total": 1000 
}

PATCH  http://localhost:3000/carrinho

DELETE http://localhost:3000/carrinho


//item-carrinho
GET http://localhost:3000/item_carrinho

GET http://localhost:3000/item_carrinho

POST http://localhost:3000/item_carrinho

PATCH  http://localhost:3000/item_carrinho

DELETE http://localhost:3000/item_carrinho


//categorias
###

GET http://localhost:3000/categorias

GET http://localhost:3000/categorias

POST http://localhost:3000/categorias
Content-Type: application/json

{
  "nome": "verdura"
}
PATCH  http://localhost:3000/categorias

DELETE http://localhost:3000/categorias

###
//pedidos
GET http://localhost:3000/pedidos

GET http://localhost:3000/pedidos

POST http://localhost:3000/pedidos

PATCH  http://localhost:3000/pedidos

DELETE http://localhost:3000/pedidos


###

//usuarios
GET http://localhost:3000/usuarios

###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Pedro",
  "email": "jvlegal@example.com",
  "senha": "112233",
  "telefone": "44444444444",
  "endereco": "bairro massa, 1000"
}

###

PATCH  http://localhost:3000/usuarios/

###

DELETE http://localhost:3000/usuarios/dev_ksvYSPaEBK48INnrbU-iJ
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXZfQldQSVNQSFhaSmxselctaGtxS21mIiwibm9tZVVzdWFyaW8iOiJHdXN0YXZvIE0iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NDgzOTIzNzEsImV4cCI6MTc0ODM5NTk3MX0.jLqenihUDmYCTv1VpVG1LXSyIGrvrwiDe6EpqheGWxk


//pagamento
GET http://localhost:3000/pagamento

GET http://localhost:3000/pagamento

POST http://localhost:3000/pagamento

PATCH  http://localhost:3000/pagamento

DELETE http://localhost:3000/pagamento


//entrega
GET http://localhost:3000/entrega

GET http://localhost:3000/entrega

POST http://localhost:3000/entrega

PATCH  http://localhost:3000/entrega

DELETE http://localhost:3000/entrega


//endereco
GET http://localhost:3000/endereco

GET http://localhost:3000/endereco

POST http://localhost:3000/endereco

PATCH  http://localhost:3000/endereco

DELETE http://localhost:3000/endereco


//avaliacao
GET http://localhost:3000/avaliacao

GET http://localhost:3000/avaliacao

POST http://localhost:3000/avaliacao

PATCH  http://localhost:3000/avaliacao

DELETE http://localhost:3000/avaliacao